replicaCount: 2

autoscaling:
  enabled: true       # Set to true to enable autoscaling
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

image:
  repository: localhost:5000/portfolio-website
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: LoadBalancer
  port: 80

serviceAccount:
  create: true
  name: portfolio-service-account

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: "myportfolio.local"
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

